#!/bin/bash

file="${1}"
temp_dir="${2}"
bakta_db="${3}"

conda activate envs/bakta

bakta --skip-plot --db "${bakta_db}" --output "${temp_dir}" --prefix "${file}" "${temp_dir}/${file}"

# What arguments do I need to write here? 

# Other possible arguments: 
# --locus LOCUS         Locus prefix (default = 'contig')
#  --locus-tag LOCUS_TAG                       Locus tag prefix (default = autogenerated)
# --threads THREADS, -t THREADS	Number of threads to use (default = number of available CPUs)
#  --tmp-dir TMP_DIR     Location for temporary files (default = system dependent auto detection)

# retrieve bakta software parameters and arguments and return in a text file for software and run 
# bakta --version > $TEMP/temp_software.txt 
# load that into the software database and then retreive the software id 

conda deactivate
